language: node_js
node_js:
    - '14.16.0'

cache: yarn

install:
    - yarn global add lerna jest
    - lerna bootstrap

matrix:
    include:
        - name: Blog Pipeline
          env: PACKAGE_LOCATION=packages/blog PACKAGE_NAME=@gatsby-monorepo/blog
        - name: Shop Pipeline
          env: PACKAGE_LOCATION=packages/shop PACKAGE_NAME=@gatsby-monorepo/shop

script:
    - cd $PACKAGE_LOCATION
    - yarn test
    - yarn build

deploy:
    provider: script
    script: now public --token $VERCEL_TOKEN
    skip_cleanup: true
    app: $PACKAGE_NAME
